# Generated by Django 4.2.6 on 2023-10-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=50)),
                ('username', models.CharField(default='DEFAULT VALUE', max_length=25)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=25)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_usuario', to='usuarios.roles')),
            ],
        ),
    ]
